### DISCUSSION TITLE
[求助] Github Action build 时报错 Reached heap limit Allocation failed

### DISCUSSION THREAD

**Discussion by dbinfun** [YunYouJun/valaxy#311] [Q&A] [answered]
使用github action 部署时，编译总是报错 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

我的valaxy版本是`0.16.2`, 文章数量大概在70篇左右；
同样的配置，在本地编译没有问题，使用valaxy `0.14.57` 在github action编译没有问题 (所以我还用着0.14.57 而无法升级)

这是我的yml配置文件
```yml
build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: 📦 Install Dependencies
        run: npm i

      - name: Set NODE_OPTIONS
        run: export NODE_OPTIONS="--max_old_space_size=10240"

      - name: 🌌 Build Valaxy Blog
        run: npm run build
```
这是具体的报错信息
```
<--- Last few GCs --->
[1849:0x666ac70]   101544 ms: Scavenge 1997.0 (2083.1) -> 1993.5 (2083.1) MB, 10.1 / 0.0 ms  (average mu = 0.526, current mu = 0.502) allocation failure; 
[1849:0x666ac70]   101564 ms: Scavenge 1998.2 (2083.1) -> 1994.5 (2083.1) MB, 10.0 / 0.0 ms  (average mu = 0.526, current mu = 0.502) allocation failure; 
[1849:0x666ac70]   101585 ms: Scavenge 2000.1 (2083.1) -> 1996.4 (2099.1) MB, 13.4 / 0.0 ms  (average mu = 0.526, current mu = 0.502) allocation failure; 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb95b60 node::Abort() [node]
 2: 0xa9a7f8  [node]
 3: 0xd6f2f0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd6f697 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf4cba5  [node]
 6: 0xf5f08d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf39[78](https://github.com/dbinfun/my-blog/actions/runs/7335938871/job/19974531396#step:6:78)e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xf3ab57 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xf1bd2a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x12e114f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x170deb9  [node]
Aborted (core dumped)
Error: Process completed with exit code 134.
```
