### ISSUE TITLE
Markdown Styles Conflict

### ISSUE THREAD

**Issue by WRXinYue** [YunYouJun/valaxy#483]
Valaxy by default applies some Markdown styles, which may cause conflicts with the theme's Markdown or Prose styles:

![image](https://github.com/user-attachments/assets/0525710a-eda9-453d-ae47-a2628f03bfa6)

Here is a temporary solution:

```scss
@use 'sass:map';

.markdown-body {
  h1, h2, h3, h4, h5, h6 {
    position: initial;
    font-weight: normal;
    outline: none;
  }

  .header-anchor {
    margin-left: initial;

    &::before {
      content: none;
      display: none;
    }
  }

  .custom-block div[class*='language-'] {
    &::before {
      content: none;
    }
  }

  .custom-block .vp-code-group .tabs {
    &::before {
      content: none;
    }
  }

  .end .line {
    &::before {
      content: none;
    }
  }
}

@media (width >= 768px) {
  .markdown-body h1 {
    letter-spacing: normal;
    line-height: normal;
    font-size: 24px;
  }
}
```
