### ISSUE TITLE
博客迁移中遇到痛点：短链接，文章加密

### ISSUE THREAD

**Issue by XMuli** [YunYouJun/valaxy#525]
### Describe the bug

新的很棒的主题，搜也聚焦聚合多个网站显示，很出彩，感谢辛苦付出

之前是多年的 hexo-yun-theme 用户，2019-至今， 今晚准备迁移到 valaxy-yun 时，遇到痛点；使得博客迁移成本变大。
**其中 1，2 是刚需，3 是一种习惯**

1. 希望支持短链接，已翻阅 #237 但是不满足。理由：此前文章相关链都是评论在网络上了，现在变成了文件名，导致链接失效。重定向也不合适。以前的 `abbrlink: c91a33` 失效了

2. 加密文章，参考 [页面加密](https://valaxy.site/guide/page#%E9%A1%B5%E9%9D%A2%E5%8A%A0%E5%AF%86)， 实测 `encryptedContent` 字段失效，不能预览解密后的提示效果。或能将下图红框此处自定义修改写一段话也行。效果图如下

![Image](https://github.com/user-attachments/assets/662ac69b-f8d4-41db-a6c7-31e682863adc)

![Image](https://github.com/user-attachments/assets/9d783325-b5dc-4498-99a0-9b6fc27e1ff7)

3. 若能支持底部 运行时间 就好了，
```
################# 运行时间 #################
  live_time:
    enable: true
    prefix: 本博客已萌萌哒地运行
    suffix: (●'◡'●)
    start_time: '2019-06-09T00:00:00'
```

参考 [valaxy-addon-components](https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy-addon-components/README.zh-CN.md) 但是未得到预期效果，可能是使用不对，还是其它原因？

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
