### ISSUE TITLE
功能请求：希望支持关闭 RSS 自动生成的配置项

### ISSUE THREAD

**Issue by JayMuShui** [YunYouJun/valaxy#539]
### Clear and concise description of the problem

目前在使用 Valaxy 进行博客构建时，`build` 命令会自动在 `build:after` 阶段生成 RSS（feed.xml/atom.xml/feed.json）文件。  
但在以下场景下，自动生成 RSS 可能会带来困扰：

- 文章 frontmatter 采用多语言对象结构
- （如 `{ zh-CN: ..., en: ... }`），会导致 RSS 生成报错（`cdata.replace is not a function`）。
- 部分用户并不需要 RSS 功能，或希望自行控制 RSS 的生成时机。
- 期望更灵活地定制构建流程，避免无用文件生成。

### Suggested solution

配置文件中，增加如下配置项：
```ts
feed: {
  enable: false
}
```

当该配置为false时，
build 阶段不再自动生成任何 RSS/Feed 文件。

### Alternative

目前我自己用的方法是：
1. 打开文件 `node_modules/.pnpm/valaxy@0.23.3_.../node_modules/valaxy/dist/chunk-OXTCPOR5.js`。
2. 找到如下代码注释并直接return：
   ```js
   setup(node) {
     node.hook("build:after", async () => {
       //console.log();
       //await build(node.options);
       return;
     });
   }
   ```

### Additional context

- 该功能对于通过JSON解析实现多语言、定制化构建流程、以及不需要 RSS 的用户非常有用。
- 目前只能通过手动修改 node_modules 或批量转换 frontmatter 字段规避，体验不佳。

感谢小云，期待采纳！

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
Try `modules.rss.enable` in `valaxy.config.ts`.

**Comment by YunYouJun** [comment]
> （如 { zh-CN: ..., en: ... }），会导致 RSS 生成报错（cdata.replace is not a function）。

这样的行为应该是不符合预期的，能否提供相关文件示例以复现。

**Comment by JayMuShui** [comment]
> > （如 { zh-CN: ..., en: ... }），会导致 RSS 生成报错（cdata.replace is not a function）。
> 
> 这样的行为应该是不符合预期的，能否提供相关文件示例以复现。

```
//自定义 utils/i18n.ts 一个函数
import { useI18n } from 'vue-i18n'

/**
 * 多语言内容接口
 */
export interface I18nContent {
  [key: string]: string
}

/**
 * 解析多语言内容
 * @param content 可能的多语言内容
 * @returns 当前语言对应的内容
 * 
 * @example
 * // 对象形式
 * parseI18nContent({ 'zh-CN': '中文', 'en': 'English' })
 * 
 * // 普通字符串
 * parseI18nContent('普通文本')
 */
export function parseI18nContent(content?: string | I18nContent | any): string {
  const { locale } = useI18n()

  if (!content) return ''
  
  // 1. 如果是对象
  if (typeof content === 'object' && content !== null) {
    // 优先使用当前语言
    if (content[locale.value]) {
      return content[locale.value]
    }
    // 其次使用中文
    if (content['zh-CN']) {
      return content['zh-CN']
    }
    // 最后使用第一个可用的语言
    const firstValue = Object.values(content)[0]
    return typeof firstValue === 'string' ? firstValue : ''
  }
  
  // 2. 如果是字符串，直接返回
  if (typeof content === 'string') {
    return content
  }
  
  // 3. 其他情况转换为字符串
  return String(content)
} 
```
作为相对来讲~~很简单粗暴的~~对markdown文章本身处理如标题、作者、标签、分类的i18n化处理，因为技术文档中只有关
```
## example {lang=zh-CN}
::: zh-CN
example
:::
```
对正文的国际化处理而不包含yml标头的处理

```
//自定义 components/YunPostCategories.vue
<template>
  <RouterLink
    v-if="categories"
    :to="{
      path: '/categories',
      query: {
        category: Array.isArray(categories) ? categories[0] : categories
      }
    }"
    class="post-category inline-flex items-center text-$va-c-text bg-$va-c-bg-soft rounded-full px-3 py-1 text-sm"
    hover="text-$va-c-primary-lighter bg-$va-c-bg-mute"
  >
    <div m="x-1" inline-flex i-ri-folder-2-line />
    <span>
      {{ Array.isArray(categories) 
        ? categories.map(cat => parseI18nContent(cat)).join(' / ') 
        : parseI18nContent(categories) }}
    </span>
  </RouterLink>
</template>
```
例如：
```
//post/example.md
---
title: 
  zh-CN: 哇，又是无所事事的一天。
  en: Wow, Another Day of Doing Nothing
icon: i-carbon-moon
color: teal 
description: 
  zh-CN: 青春、乡愁与数字时代的自我反思随笔
  en: An Essay on Youth, Nostalgia, and Self-Reflection in the Digital Age
author: 
  zh-CN: 沐
  en: Mu
date: 2025-04-18 01:12:00
updated: 2025-04-18 01:12:00
toc: true
aside: false
tags:
  - {"zh-CN": "乡愁", "en": "Nostalgia"}
  - {"zh-CN": "自我反思", "en": "Self-Reflection"}
  - {"zh-CN": "心理健康", "en": "Mental Health"}
  - {"zh-CN": "社交媒体", "en": "Social Media"}
  - {"zh-CN": "青春", "en": "Youth"}
  - {"zh-CN": "时间停滞感", "en": "Time Stagnation"}
  - {"zh-CN": "数字时代", "en": "Digital Age"}
  - {"zh-CN": "存在主义焦虑", "en": "Existential Anxiety"}
categories:
  - {"zh-CN": "随笔", "en": "Essays"}
---
其他内容
```
