### ISSUE TITLE
index.scss中自定义样式时部分失效

### ISSUE THREAD

**Issue by DaBiGu** [YunYouJun/valaxy#552]
### Describe the bug

在项目文件夹下`valaxy-blog/styles/index.scss`中自定义了如下样式
```css
:root {
  --va-c-primary: #485ab8;
  --va-c-primary-lighter: #9edafa;
  --va-c-bg-light: rgba(255, 255, 255, 0.6);
}
```
渲染结果如下：
![Image](https://github.com/user-attachments/assets/9614d524-8bc4-4dea-9bc5-ce0c13f09f97)
![Image](https://github.com/user-attachments/assets/d8aa7e1d-b10a-4384-b8fd-2391099162ad)

自定义颜色在两种模式下都生效；而背景透明度在light模式下生效，dark模式下不生效
inspect查看在dark模式下卡片确实是`bg="$va-c-bg-light"`

### Reproduction

pnpm create valaxy 后的默认主题下仅修改/styles/index.scss (和背景图片以测试透明度)

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (24) x64 AMD Ryzen 9 7900X 12-Core Processor
    Memory: 8.29 GB / 31.16 GB
  Binaries:
    Node: 22.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.4.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.11.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.26100.1882
```

### Used Package Manager

pnpm

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
由于 亮暗 背景色通常是不一样的，如果你希望覆盖暗色模式下的背景，你需要这么写：

> https://valaxy.site/guide/custom/styles#%E8%A6%86%E7%9B%96%E6%9A%97%E8%89%B2%E6%A8%A1%E5%BC%8F

```css
html.dark {
  --va-c-bg: #1a1a1d;
  --va-c-bg-light: #202127;
  --va-c-bg-dark: #1a1a1a;
  --va-c-bg-opacity: rgba(0, 0, 0, 0.8);
  --va-c-bg-alt: #161618;
  --va-c-bg-soft: #202127;
  --va-c-bg-mute: #2f2f2f;
}
```

**Comment by DaBiGu** [comment]
添加
```css
html.dark {
  --va-c-bg-light: rgba(32, 33, 39, 0.8);
}
```
后实现了想要的效果。
